[tool.poetry]
name = "predict_albedo"
version = "0.1.0"
description = "Predict albedo"
authors = ["Christina Draeger"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
